name: generate animation

on:
  # Her 24 saatte bir otomatik çalışır
  schedule:
    - cron: "0 */24 * * *" 
  
  # Manuel olarak başlatabilmeni sağlar
  workflow_dispatch:
  
  # Main branch'e her kod yüklediğinde çalışır
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Yılan animasyonunu oluşturur
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: nehirtosun238-dot
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#8A2BE2&color_dots=#161b22,#4c2885,#632ca6,#7b2ed0,#9530ff
            
      # Oluşan dosyayı 'output' isimli gizli bir dala (branch) yükler
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
